<?php

namespace app\controllers;

use app\components\message\Language;
use app\models\About;
use app\models\Contact;
use app\models\Product;
use app\models\Service;
use Yii;
use app\models\News;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller
{

    public function behaviors()
    {
      return [
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'delete' => ['POST'],
                  'logout' => ['POST'],
              ],
          ],
      ];
    }
    public function beforeAction($action)
    {
        $config = Yii::$app->cache->get('config_'.\app\components\message\Language::getLanguageNum());
        if(empty($config))
        {
            $config = getWebConfig();
            Yii::$app->cache->set('config_'.\app\components\message\Language::getLanguageNum(), $config);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    //首页
    public function actionIndex()
    {

        $config = Yii::$app->cache->get('config_'.\app\components\message\Language::getLanguageNum());


      return $this->render('index', ['config'=>$config]);
    }

    /**
     * 关于我们
     * @return string
     */
    public function actionAbout()
    {
        $model = About::findOne(Language::getLanguageNum());
        return $this->render('about',['model'=>$model]);
    }

    /**
     * 联系我们
     * @return string
     */
    public function actionContact()
    {
        $model = Contact::findOne(Language::getLanguageNum());
        return $this->render('contact',['model'=>$model]);
    }
    /**
     * 新闻列表
     * @return string
     */
    public function actionNews()
    {
        $model = new News();
        $ret = $model::getList();
        if($ret['success'])
        {
            $list = $ret['list'];
            $pages = $ret['pages'];
            return $this->render('newsList',[
                'model' => $model,
                'list' => $list,
                'pages' => $pages,
            ]);
        }
        else
        {
            return $this->render('newsList',['list'=>[]]);
        }

    }

    /**
     * 新闻详情
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionNewsDetail($id)
    {
        $model = News::getDetail($id);
        if (empty($model)) {
            return $this->redirect(['news']);
        } else {
            return $this->render('newsDetail', ['model' => $model]);
        }
    }

    /**
     * 产品列表
     * @return string
     */
    public function actionProduct()
    {
        $model = new Product();
        $ret = $model::getList();
        if($ret['success'])
        {
            $list = $ret['list'];
            $pages = $ret['pages'];
            return $this->render('productList',[
                'model' => $model,
                'list' => $list,
                'pages' => $pages,
            ]);
        }
        else
        {
            return $this->render('productList',['list'=>[]]);
        }

    }

    /**
     * 产品详情
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionProductDetail($id)
    {
        $model = Product::getDetail($id);
        if (empty($model)) {
            return $this->redirect(['product']);
        } else {
            return $this->render('productDetail', ['model' => $model]);
        }
    }

    /**
     * 服务项目列表
     * @return string
     */
    public function actionService()
    {
        $model = new Service();
        $ret = $model::getList();
        if($ret['success'])
        {
            $list = $ret['list'];
            $pages = $ret['pages'];
            return $this->render('serviceList',[
                'model' => $model,
                'list' => $list,
                'pages' => $pages,
            ]);
        }
        else
        {
            return $this->render('serviceList',['list'=>[]]);
        }

    }

    /**
     * 服务项目详情
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionServiceDetail($id)
    {
        $model = Service::getDetail($id);
        if (empty($model)) {
            return $this->redirect(['service']);
        } else {
            return $this->render('serviceDetail', ['model' => $model]);
        }
    }

    //------------------------------------------------------------------------//

    //仅用于测试
    public function actionTest()
    {
      //Share::deleteAll(['nickname'=>NULL]);
      //return $this->renderPartial('test');
    }

    //公众号关注订阅
    public function actionSubscribe()
    {
      return $this->renderPartial('subscribe');
    }

    public function actionLogout()
    {
      Yii::$app->user->logout();
      return $this->redirect('/admin/user/login');
    }

    //错误显示页
    public function actions()
    {
      return [
        'error' => [
          'class' => 'yii\web\ErrorAction',
        ],
      ];
    }


}
